### ISSUE TITLE
[Pages] Option to store your search in GetAPI for others to see

### ISSUE THREAD

**Issue by basicallydan** [basicallydan/forkability#10]

**Comment by M-Zuber** [comment]
So what is going on with this?

**Comment by basicallydan** [comment]
@M-Zuber Let's get rid of it for now. My ambition was for GetAPI to be a simple key/value store and Forkability could use it for that, but I haven't gotten round to it because life got in the way. I'll resuscitate it once I've made some progress with GetAPI :)
