### ISSUE TITLE
c# support

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#36]
I have started to work on implementation for c# support.
Input into to what should be checked would be greatly appreciated

**Comment by M-Zuber** [comment]
The `.csproj` file requirement is going to be a slight difficulty due to `Asp.Net 5` wherein the file doesn't exist.
Maybe we should consider adding `suggested features`?

**Comment by basicallydan** [comment]
@M-Zuber Oh dear! Hmm. Could do. I guess there's no way to detect if it's .Net 5 or .Net 4?

**Comment by M-Zuber** [comment]
I'm not sure. I have not started using the `.Net 5` yet myself, but I did [this](https://twitter.com/mordzuber/status/593134047171190784), lets see what happens.

**Comment by M-Zuber** [comment]
While I never got a reply I believe that it has been replaced completely by `project.json`.
The question then becomes how do we allow - for one key - a set of values that if any one of them is a match then we are good to go?

**Comment by basicallydan** [comment]
Hey @mzuber! I was talking to someone from my old company about these
changes the other night and I thought about this issue - but yeah! It works!

The way we do it is that the value can be a regular expression. For
example, for checking for a licence:

```
'Licence document': /^(licen[cs]e|copying)/i,
```

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by M-Zuber** [comment]
took care of that one see #50

**Comment by M-Zuber** [comment]
I think we can close this, if other c# related things come up they can go in a new issue

**Comment by basicallydan** [comment]
Cool sounds good thanks for closing :thumbsup:
