### ISSUE TITLE
Lint for test suite not working

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#44]
If I run `forkability` on [this repo of mine](https://github.com/M-Zuber/VirtualGabbai) repo ( -see [here](http://basicallydan.github.io/forkability/?u=M-Zuber&r=VirtualGabbai&l=csharp)), it gives me a fail on my test suite. Even though one exists [here](https://github.com/M-Zuber/VirtualGabbai/tree/master/VirtGabbai/Unit%20Tests).
Is it a nesting problem?

**Comment by basicallydan** [comment]
Huh. Yeah, I think it is. Maybe there should be an option to search a certain depth for certain things.

Good spot!

**Comment by M-Zuber** [comment]
Somewhat embarrassingly, it seems the check I added for a `.csproj` file is also failing for some odd reason.... :flushed:

**Comment by basicallydan** [comment]
Hahah! Well, same problem I guess! No need to be embarasse!

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by M-Zuber** [comment]
So after digging a little it seems that the code is correct (see #45 for example).
The problem is the that the following is returned from the call to this github api hook https://api.github.com/repos/m-zuber/VirtualGabbai/git/trees/dd0400997913a3e988c5a9dfb0e05dc074687b6c

```json
{
  "sha": "dd0400997913a3e988c5a9dfb0e05dc074687b6c",
  "url": "https://api.github.com/repos/M-Zuber/VirtualGabbai/git/trees/dd0400997913a3e988c5a9dfb0e05dc074687b6c",
  "tree": [
    {
      "path": ".gitattributes",
      "mode": "100644",
      "type": "blob",
      "sha": "412eeda78dc9de1186c2e0e1526764af82ab3431",
      "size": 483,
      "url": "https://api.github.com/repos/M-Zuber/VirtualGabbai/git/blobs/412eeda78dc9de1186c2e0e1526764af82ab3431"
    },
    {
      "path": ".gitignore",
      "mode": "100644",
      "type": "blob",
      "sha": "b188f62bcfc1531acfa2c14edd4e94876fad2033",
      "size": 2782,
      "url": "https://api.github.com/repos/M-Zuber/VirtualGabbai/git/blobs/b188f62bcfc1531acfa2c14edd4e94876fad2033"
    },
    {
      "path": "DataBase",
      "mode": "040000",
      "type": "tree",
      "sha": "0958079ebfed6e7aefa69a318cd4c2be87403dcd",
      "url": "https://api.github.com/repos/M-Zuber/VirtualGabbai/git/trees/0958079ebfed6e7aefa69a318cd4c2be87403dcd"
    },
    {
      "path": "Design Files",
      "mode": "040000",
      "type": "tree",
      "sha": "2fd039b66d4d6f1e3a38b523a7a651be0046c3bb",
      "url": "https://api.github.com/repos/M-Zuber/VirtualGabbai/git/trees/2fd039b66d4d6f1e3a38b523a7a651be0046c3bb"
    },
    {
      "path": "README.md",
      "mode": "100644",
      "type": "blob",
      "sha": "af98547768020a0d71cb9bc608c5da996920dd3a",
      "size": 248,
      "url": "https://api.github.com/repos/M-Zuber/VirtualGabbai/git/blobs/af98547768020a0d71cb9bc608c5da996920dd3a"
    },
    {
      "path": "VirtGabbai",
      "mode": "040000",
      "type": "tree",
      "sha": "466fb9df2506fa1a7cf16c09a8d9502b0b9abfd6",
      "url": "https://api.github.com/repos/M-Zuber/VirtualGabbai/git/trees/466fb9df2506fa1a7cf16c09a8d9502b0b9abfd6"
    }
  ],
  "truncated": false
}
```

**Comment by M-Zuber** [comment]
After following the links in each item in the results, it keeps digging deeper. And then you can get to nested items.
Although this doesn't explain why it works in test and not real...

**Comment by basicallydan** [comment]
@M-Zuber I think I'll have to try and reproduce this later. Very strange indeed =\

**Comment by M-Zuber** [comment]
I have a theory why it works in the tests.
Since we are mocking the `sha` with individual parts of the tree, even nested items are showing up on the same level.

So a fix would have to include fixes to the mocking system.

**Comment by basicallydan** [comment]
Aha! Yeah I bet that's it! Right. I'll see what I can do. Once that's sorted it should be easier to figure out why it's not working in real life.

**Comment by M-Zuber** [comment]
So..... a small complication.
While working on a fix, I realized that there has to be a check that if something passes, it should not also fail.
Meaning -if at the upper level of a `c#` project there is a `Readme` - that is a pass. But when we drill in a level to find the `.csproj`, on the second pass there is no `Readme`.
Solutions?

**Comment by basicallydan** [comment]
Good spot. My first instinct is this: The `passes` and `failures` arrays in `lintFiles` might need to be passed around into the recursive checks. What do you think?

**Comment by basicallydan** [comment]
Ugh, okay, this is a tough one, might require a bit of restructuring. I think the best solution is to do the following:

1. In `app.js`, allow a `treeDepth` option to be passed to forkability
2. When the tree is being downloaded, use `treeDepth` to recursively make requests to all the `type === 'tree'` items, and populate a `tree` property on each item with whatever the response from the API is
3. Pass this to `lintFiles`
4. `lintFiles` checks if an item on a tree has a populated `tree` property, and if so, recursively go into that on the `lintFiles` function.

This avoids having to give `lintFiles` a dependency on `request`, and thus needing to do any async or promises stuff, which is nice. It does mean a bit of restructuring of `app.js` though.

What do you think?

I don't mind whether you or I do this, but I'm probably not gonna do it right now - maybe after work some time this week or later today - so what I'd say is if either of us decide to sit down and bash it out, just to put a note here so that the other doesn't get in the way or repeat work. Agreed? :)

**Comment by M-Zuber** [comment]
The architecture sounds right. I'll put something here if I start working on it

**Comment by M-Zuber** [comment]
As far as overriding of passes/failures, I think it will be easier to come up with a proper solution once the linting is more concrete

**Comment by basicallydan** [comment]
:thumbsup: Coolio!

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by M-Zuber** [comment]
I've started to try and fix this. I might even be close to a working solution.

**Comment by basicallydan** [comment]
Wow, amazing! Nice one, thanks for picking it up so fast!

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by M-Zuber** [comment]
See #46.

There is still more testing that I plan on doing. I will let you know when I think it is tested enough

**Comment by M-Zuber** [comment]
This
```js
'Readme document': /^readme/i,
```
forces the `readme` to be at the top level.
Comments?

**Comment by basicallydan** [comment]
Hmm, I think that it makes sense to insist that there is a readme at the top level. If there wasn't, then it wouldn't give the viewer/reader/contributor/whatever immediate information about the repository. What do you think?

**Comment by M-Zuber** [comment]
It sounds correct to me.
The only question is, do we allow adding a setting similar to `shouldExist` -or is it dependent on the `regular expression`?

I personally feel that it should depend on the `regex`.

**Comment by M-Zuber** [comment]
I think I finished the file linting at a depth. See #46.

**Comment by M-Zuber** [comment]
Closing due to success of #47

**Comment by basicallydan** [comment]
@M-Zuber Thanks for doing this closing of stuff!
