### ISSUE TITLE
.gitignore changes to due personal work space choices

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#52]
I have started working on this using `vs code`. It has added typings files and ect to the project.
Should I change the .gitignore or rely on myself to pay attention manually?

**Comment by basicallydan** [comment]
Yeah defo change the gitignore if that's the case!

I think it might be a good idea to make you a collaborator on the github project if you want, since you seem to have a pretty good idea of goals by now and seem to enjoy writing tests enough :) what do you think?

**Comment by M-Zuber** [comment]
Sounds awesome. Thank you! 
Do you want to define privileges/obligations first?

**Comment by basicallydan** [comment]
@M-Zuber Sorry this took so long. Hah, been either preparing to move country, moving, or being on holiday! Crazy times!

Anyway, let's see. I think by now you get the main goals of the project, but in case it needs clarifying it's [here in the readme](https://github.com/basicallydan/forkability#long-term-goals-of-this-project). I think that's all that needs to be said really, any changes which you feel will contribute to the goals are cool. I'll keep control over the NPM module now, meaning only I can publish new versions.

As far as this repo is concerned, how about for large changes (i.e. new organisational/branch structures of the repo) let's discuss first, but for bug fixes and planned features, if you make any just push them, let me know and I'll cut a new version.

And make sure to keep things well-tested! If it's a new feature, put a test in for it first, and if it's a new language then put in a whole new suite of tests for it. That sorta thing.

And if anything is unclear, lemme know? Sounds cool?

**Comment by M-Zuber** [comment]
Sounds cool. I am assuming the main location for discussion would be `gitter`?

**Comment by basicallydan** [comment]
Right you are!

**Comment by basicallydan** [comment]
Oh, well, it depends on the thing. For little convos yeah, but if we're talking new features and major bugs lets talk on GitHub in the appropriate issue/PR :)
