### ISSUE TITLE
Badge for forkability.io

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#53]
Creating a badge will allow repo owners to indicate their forkability score in the README

**Comment by M-Zuber** [comment]
[Also opened this] (https://github.com/badges/shields/issues/502)

**Comment by basicallydan** [comment]
Okay, I really wanna do this today based on the conclusion of the conversation in that thread, but #54 and #55 are easier and I'm sleepy so they are now priority!

**Comment by M-Zuber** [comment]
Do you still want to take it? I'm guessing it's a simple if positives are more then 90% of results we generate green otherwise nothing for starters?

**Comment by basicallydan** [comment]
Yeah I agree. I'd like to do this, yeah ^^ Tonight. Just had some bad news
about a visa and I'm looking forward to some furious programming when I'm
finished with the day's chores :P

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by M-Zuber** [comment]
visas suck :(
Good luck with the chores :grinning:

**Comment by basicallydan** [comment]
Just realised the URL generated for the badge doesn't link to the correct page - it doesn't include language!
