### ISSUE TITLE
Spelling of license

### ISSUE THREAD

**Issue by montanaflynn** [basicallydan/forkability#54]
Hello, thanks for the cool project :trophy: 

When I ran my project I noticed what I thought was a typo: "licence". I was going to submit a PR but since I found 50+ spelling occurrences I did a little research it appears this is the British spelling (along with Canada, New Zealand and some other countries) but not the common spelling used on GitHub, including forkability's own `LICENSE` file.  I would suggest changing it but of course it's up to you!

**Comment by basicallydan** [comment]
Hello, and thanks!

Good spot! Consistency is probably preferable in this case, I agree. Although it'd be cool to reflect what the repo contains in case it *does* use the British spelling.

I'll try and get round to that in a few hours, I have some appointments but if you get there sooner feel free to raise a PR. In case you haven't already been looking into it you wanna look in `lintFiles.js`.

Cheers :)

**Comment by basicallydan** [comment]
I have changed the spelling from one correct variety to another correct variety :+1:
