### ISSUE TITLE
User comparison should be lowercase 

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#59]
see [here](https://www.reddit.com/r/opensource/comments/3j7n5q/is_your_github_repository_welcoming_to_newcomers/cun4fkl).

Related to #57 

Places to fix:
- [line 5](https://github.com/basicallydan/forkability/blob/11519b2c390b520987e47607bc34ceb0bafa4628/lib/lintIssues.js#L5)
- [line 16](https://github.com/basicallydan/forkability/blob/11519b2c390b520987e47607bc34ceb0bafa4628/lib/lintIssues.js#L16)

Anywhere else the change should be added?

**Comment by basicallydan** [comment]
Not in anywhere that the user is concerned, nope - I can't find anything, anyway.

**Comment by Alshie** [comment]
Hello,

I've submitted a pull request for this. First time I have ever been through this process so hopefully I have done correctly.

**Comment by M-Zuber** [comment]
So far you are doing great. :smile:
I left you some feedback back at the PR
