### ISSUE TITLE
Projects with multiple languages 

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#62]
What is the current behavior for a project with multiple languages? 
What is the desired behavior?

**Comment by basicallydan** [comment]
At the moment you choose a primary language, and it bases the whole thing
on that. I think that's probably a good behaviour for now tbh. Does it make
sense to judge a project by multiple different standards? I don't think
it'd hurt and we could just run the linter multiple times to do it.

I wonder if this is a problem many people have - have you come across it?

**Comment by M-Zuber** [comment]
> I have not come across it, but I am trying to build up some issues in light of the `Open source contribution events` coming up 

There definitely exists a class of a projects with architecture that uses mixes of different technology / languages  (eg. front-end vs back-end).
Running the linter multiple times sounds good to me.

I propose the following behavior:
- The user picks a language (maybe multiple?) ==> we lint only by the users choice
- No language is picked ==> for every language in the project that we have a linter for -we run it

**Comment by basicallydan** [comment]
@M-Zuber So for the first behaviour, I think we definitely would want the user to pick multiple languages. The complexity of user options should end there for now, probably.

I actually think I "implemented" multiple-language support before but it seems like I did it wrong. It doesn't work!

For instance:

```
forkability basicallydan/forkability -l nodejs,python
```

This should work. I'll write some tests to figure out why it's not working, fix it, then put it into the web UI with checkboxes (unless you're not a fan of this idea - let me know). Hopefully I can do this this afternoon, I have a few hours until my next plane.

We may want to change the feedback too, to say which requirement fits with which language, but let's decide once these changes to the options and web UI are done.

**Comment by M-Zuber** [comment]
Either check-boxes or a select with the multiple attribute set.

Do we make any changes to the list based on an answer from the `GitHub` api? 
or just show languages we have linters for?
and if the user chooses something irrelevant to their project we don't really care 
(I actually think we might want this option as it might be useful for users that have a project in a language we don't officially support, but rules from another lang are relevant)

Agree that updating the feedback should probably be done, also agree that it can wait :smile:

**Comment by basicallydan** [comment]
Oh yeah a select box with multiple! Fuck yeah, I forgot what our audience is.

We do actually check at one point what languages the repo contains. Check out [these lines](https://github.com/basicallydan/forkability/blob/master/lib/app.js#L100-L107), which are really just there to determine whether there's any code in the repo or not.

As an aside, I'm curious which open-source contribution events you have in mind. I'm aware of two, I believe. Maybe let's talk about this on [gitter](https://gitter.im/basicallydan/forkability). I'm glad you brought this up - Forkability can really play a role in events like this!

**Comment by basicallydan** [comment]
Okay fixed it. Currently publishing to NPM. Version 0.16.1. Sorry I didn't PR this, just forgot! Publishing is taking an awfully long time though. I suspect the airport WIFI is finding this whole experience a little odd.

**Comment by basicallydan** [comment]
Alright done! Lookit: http://basicallydan.github.io/forkability/?u=basicallydan&r=forkability&l=nodejs,python

It fails because Python!

If you're happy with this, go ahead and close. I gotta get on a plane :airplane: :baggage_claim:

**Comment by M-Zuber** [comment]
Have a safe flight.
I'll try and eyeball it tonight

**Comment by M-Zuber** [comment]
I updated the tests #63

Sorry for doing on the main repo, i only realized when I went to make the PR

**Comment by basicallydan** [comment]
@M-Zuber No problem dude I do this sorta thing all the time. Cheers for making them better!
