### ISSUE TITLE
Lint for Code of Conduct

### ISSUE THREAD

**Issue by Charlotteis** [basicallydan/forkability#67]
How do we feel about adding "has a code of conduct" to the feature detection?

**Comment by M-Zuber** [comment]
Is there a standard for the file name?

**Comment by Charlotteis** [comment]
CODEOFCONDUCT / CODE-OF-CONDUCT is what I have seen

**Comment by M-Zuber** [comment]
SGTM. you want to do it? 

I can try and put together a first timer friendly issue, but not until tomorrow - earliest.

**Comment by M-Zuber** [comment]
On mobile, so can't edit. 
I meant if you don't want to do it.

**Comment by Charlotteis** [comment]
I don't have the time now, but could maybe get to it Fri/Sat/Sun? :)
If you are able to prepare a first-timer-friendly issue, that'd be awesome. Thanks for your help!

**Comment by basicallydan** [comment]
@Charlotteis Welcome to Forkability, good to see you! :+1: :+1: :D

Code of Conduct sounds like a good idea. It might be something we should make a flag too - let's see how it plays out, some people might think it's a bit much. I'm actually not too familiar with existing code of conduct files people use. Do you know any good examples?

I'm sorta wondering how it might be different from a CONTRIBUTING file, I suppose it's more about community though right?

**Comment by M-Zuber** [comment]
@basicallydan how do you feel about a third level of `strongly suggested`?
(although I think that should wait until #30  and related are taken care of)

As a reference here are some Code of Conducts I have bookmarked as nice examples (in my opinion at least)
- http://www.openssl.org/community/conduct.html
- https://golang.org/conduct
- https://github.com/mono/mono/blob/master/code_of_conduct.md

**Comment by Charlotteis** [comment]
E.G. Chai have just added one today, using the Contributor Covenant: https://github.com/chaijs/chai/blob/master/CODE_OF_CONDUCT.md

**Comment by Charlotteis** [comment]
Also, hai :)

**Comment by M-Zuber** [comment]
@Charlotteis see #79

**Comment by M-Zuber** [comment]
closed with #84 
Thank you @Charlotteis for your work
