### ISSUE TITLE
Check Git branch naming conventions.

### ISSUE THREAD

**Issue by thinkingmedia** [basicallydan/forkability#68]
Check for the use of common Git naming practices like "features/name" or "v3.3"

**Comment by M-Zuber** [comment]
I'm not so sure about this one. 
I think it might be a little too individual. 
@basicallydan what do you think?

**Comment by thinkingmedia** [comment]
actually, that is true. feature branches can exist on the fork,  but are not required from the origin.

**Comment by basicallydan** [comment]
Hey @thinkingmedia I'm afraid I agree with @M-Zuber. Sorry to burst your bubble. Thanks for the suggestion though, we do really appreciate it :+1:

**Comment by thinkingmedia** [comment]
No problem. I can see how this would be a personal preference.
