### ISSUE TITLE
Test for Code of Conduct

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#79]
Steps to implement:
- Fork the repo
- Run `git checkout code-of-conduct` to make sure you are on the correct branch
- Run `make deps` or `npm install` if you do not have make installed
- Run `npm test` and watch tests fail
- Add `'Code of Conduct':/^CODEOFCONDUCT|CODE-OF-CONDUCT|CODE_OF_CONDUCT/i,` to the  `files` object in `./lib/lintFiles.js`

Some tests will also need to be updated:
- [helper.mockResponses.js](https://github.com/basicallydan/forkability/blob/master/spec/helper.mockResponses.js#L24)
 - Update the object to include: `path: 'CODEOFCONDUCT'`

- [app.test.js](https://github.com/basicallydan/forkability/blob/master/spec/app.test.js)
 - First three tests
   - Add `report.passes.should.containEql({ message: '.gitignore file' });`
    - Update `report.passes.should.have.a.lengthOf(8);` to 9
 - `'should warn about tag failures and include a fail badge'`
    - Update `report.passes.should.have.a.lengthOf(7);` to 8
 - `'should include a fail badge if < 90% of the items are successes'`
     - Update `report.passes.should.have.a.lengthOf(6);` to 7
 - `'should include a success badge if >= 90% of the items are successes'`
     - Update `firstCommitTreeBody` to include `path: 'codeofconduct.md'`
     - Update `report.failures.should.have.a.lengthOf(10);` to 11
 - `'should allow multiple languages to be used for linting - fails due to one of the languages'`
     - Update `report.failures.should.have.a.lengthOf(2);` to 3
 - `'should include a success badge if >= 90% of the items are successes'`
     - Update `firstCommitTreeBody` to include `path: 'codeofconduct.md'`
     - Update `report.failures.should.have.a.lengthOf(13);` to 14

**Comment by basicallydan** [comment]
Amazing issue :100: You even made a `code-of-conduct` branch! What a pro.

**Comment by Charlotteis** [comment]
:clap: :clap:

**Comment by andrew** [comment]
FYI The "fork the repo" link goes to the new issue form

**Comment by M-Zuber** [comment]
It seems that I do not have a way to make that link work, so I am removing it :disappointed:

**Comment by Charlotteis** [comment]
I'd quite like to do this myself if there are no takers? Being the Christmas period and all. Not sure if this was for complete beginners or those just new to to the forkability project? :D

**Comment by Charlotteis** [comment]
I gave it a go and there were a couple errors in your write up:

`Add report.passes.should.containEql({ message: '.gitignore file' });` should be `Add report.passes.should.containEql({ message: 'Code of Conduct' });

`'should include a success badge if >= 90% of the items are successes'` on the last line should be `should allow multiple languages to be used for linting - all languages pass`. 

PR incoming but feel free to disallow it, I wanted to just get a feel for this project :)

**Comment by Charlotteis** [comment]
Also need to note that a newcomer cant push to the code-of-conduct branch and actually has to fork this repo, checkout a branch from the code-of-conduct branch and then do their code. :sparkles:

**Comment by M-Zuber** [comment]
I'll answer in order that you wrote :
For me first timers only usually means new to OSS, but in the Christmas spirit and since you where the catalyst for it,  have fun. 

Thank you for the catch of the errors in the write up. Such is the way of the copy and paste. 

I thought the first step being "fork the repo" was good enough, but the matter has been noted for further issues. Would you say it is better to include cli specific instructions or just general description of the fork, pull down, check out branch flow? 
I also didn't specify what branch to make the PR against..

**Comment by Charlotteis** [comment]
You know the "fork" part is my bad, I didn't see it for some reason. D:
I think what you put was fine.

**Comment by Charlotteis** [comment]
Just to elaborate on "first timers only"
For me, it's both new to the project and "new to OSS". Either is fine with me, just thought'd I'd make it clear that when yourfirstpr tweets its with the open that all sorts of people will come and contribute :)

**Comment by M-Zuber** [comment]
Yeah, 
I definitely wouldn't ask someone if they have ever contributed before. 
The way I see it the first timer status is a matter of a comfort level not PR count :D
Thanks again for the contribution and for the work you put into yourfirstpr. 
Going to sleep now. See ya'll after the weekend
