### ISSUE TITLE
Looking in GitHub Wiki

### ISSUE THREAD

**Issue by hughrawlinson** [basicallydan/forkability#94]
I have a repo that uses the Wiki for contributing guidelines and the code of conduct. These are pointed both pointed to from a dedicated section in the readme, so it seems to me that they're visible enough to potential contributors.

Would it be worth considering adding support for looking for these documents in repos wikis?

**Comment by M-Zuber** [comment]
There is no API for looking at wikis unfortunately.

But maybe something like #58?

**Comment by hughrawlinson** [comment]
Yeah, it'd require [cloning the wiki repository](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/). Probably best to just use standard files 😄
