### ISSUE TITLE
Sign in with GitHub not working

### ISSUE THREAD

**Issue by spences10** [basicallydan/forkability#98]
Hi,

Can't seem so sign in with GitHub, I tried on Chrome 50, Chrome 56 and on my Android phone, none of them work.

![forkability](https://cloud.githubusercontent.com/assets/234708/23228195/982e6334-f933-11e6-8d16-10f0d3476995.gif)

**Comment by basicallydan** [comment]
Hi,

Thanks for opening an issue! It's probably an SSL thing, is the browser
giving you any SSL errors?

**Comment by spences10** [comment]
This is the console output when I try from Chrome 50

The only other browser I can test on is IE11 :grimacing: 

![image](https://cloud.githubusercontent.com/assets/234708/23252663/9199c89e-f9a9-11e6-98c2-18153cd8b7ed.png)

**Comment by basicallydan** [comment]
Yep, defo an SSL cert error! I'll get this sorted ASAP. Currently in an
airport lounge in Japan so I can't promise anything but it should be
straightforward. Thanks for reporting :) I'll let you know when I'm done!

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by basicallydan** [comment]
Ah no - it's not *quite* an SSL error after all. It's the site I use for
oauth, which I also manage - I'll just make sure it's running.

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by spences10** [comment]
Closing this, doesn't seem to be being maintained any more

**Comment by basicallydan** [comment]
Sorry Scott, I'd like to but haven't found time to sort it!

**Comment by spences10** [comment]
Hey @basicallydan feel free to open your own issue to resolve it, I'm no longer interested in it being resolved.

Many thanks :+1:

**Comment by basicallydan** [comment]
Cool, cheers Scott :)

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>
